### ISSUE TITLE
ブラウザバックをすると真っ白のページが表示される…?

### ISSUE THREAD

**Issue by Hikali-47041** [Chipsnet/minato86.me#3]
![image](https://user-images.githubusercontent.com/34558365/79295035-a86bd700-7f12-11ea-9b6e-eb7a680189e3.png)
![image](https://user-images.githubusercontent.com/34558365/79295043-ae61b800-7f12-11ea-8c66-18ad61758f33.png)
![image](https://user-images.githubusercontent.com/34558365/79295051-b3266c00-7f12-11ea-87d1-0204589a50c7.png)
![image](https://user-images.githubusercontent.com/34558365/79295068-bb7ea700-7f12-11ea-840b-ea4a69182a0b.png)
ブラウザバックをしたときに`section id="main" class="main"`のなかの`style="display:none;"`が消えていないのだと思います。(違ったらすいません。)

**Comment by Chipsnet** [comment]
このissue完全に見逃してた・・・・
サイト改装することになったので閉じます
ありがとうございました🙏
